const PengunjungMall = [
  {
    ID_Pelanggan: '1',
    Gender: 'Pria',
    Usia: '19',
    Pendapatan_Tahunan_Ribuan_USD: '15',
    Pengeluaran_USD: '39',
  },
  {
    ID_Pelanggan: '2',
    Gender: 'Pria',
    Usia: '21',
    Pendapatan_Tahunan_Ribuan_USD: '15',
    Pengeluaran_USD: '81',
  },
  {
    ID_Pelanggan: '3',
    Gender: 'Wanita',
    Usia: '20',
    Pendapatan_Tahunan_Ribuan_USD: '16',
    Pengeluaran_USD: '6',
  },
  {
    ID_Pelanggan: '4',
    Gender: 'Wanita',
    Usia: '23',
    Pendapatan_Tahunan_Ribuan_USD: '16',
    Pengeluaran_USD: '77',
  },
  {
    ID_Pelanggan: '5',
    Gender: 'Wanita',
    Usia: '31',
    Pendapatan_Tahunan_Ribuan_USD: '17',
    Pengeluaran_USD: '40',
  },
  {
    ID_Pelanggan: '6',
    Gender: 'Wanita',
    Usia: '22',
    Pendapatan_Tahunan_Ribuan_USD: '17',
    Pengeluaran_USD: '76',
  },
  {
    ID_Pelanggan: '7',
    Gender: 'Wanita',
    Usia: '35',
    Pendapatan_Tahunan_Ribuan_USD: '18',
    Pengeluaran_USD: '6',
  },
  {
    ID_Pelanggan: '8',
    Gender: 'Wanita',
    Usia: '23',
    Pendapatan_Tahunan_Ribuan_USD: '18',
    Pengeluaran_USD: '94',
  },
  {
    ID_Pelanggan: '9',
    Gender: 'Pria',
    Usia: '64',
    Pendapatan_Tahunan_Ribuan_USD: '19',
    Pengeluaran_USD: '3',
  },
  {
    ID_Pelanggan: '10',
    Gender: 'Wanita',
    Usia: '30',
    Pendapatan_Tahunan_Ribuan_USD: '19',
    Pengeluaran_USD: '72',
  },
  {
    ID_Pelanggan: '11',
    Gender: 'Pria',
    Usia: '67',
    Pendapatan_Tahunan_Ribuan_USD: '19',
    Pengeluaran_USD: '14',
  },
  {
    ID_Pelanggan: '12',
    Gender: 'Wanita',
    Usia: '35',
    Pendapatan_Tahunan_Ribuan_USD: '19',
    Pengeluaran_USD: '99',
  },
  {
    ID_Pelanggan: '13',
    Gender: 'Wanita',
    Usia: '58',
    Pendapatan_Tahunan_Ribuan_USD: '20',
    Pengeluaran_USD: '15',
  },
  {
    ID_Pelanggan: '14',
    Gender: 'Wanita',
    Usia: '24',
    Pendapatan_Tahunan_Ribuan_USD: '20',
    Pengeluaran_USD: '77',
  },
  {
    ID_Pelanggan: '15',
    Gender: 'Pria',
    Usia: '37',
    Pendapatan_Tahunan_Ribuan_USD: '20',
    Pengeluaran_USD: '13',
  },
  {
    ID_Pelanggan: '16',
    Gender: 'Pria',
    Usia: '22',
    Pendapatan_Tahunan_Ribuan_USD: '20',
    Pengeluaran_USD: '79',
  },
  {
    ID_Pelanggan: '17',
    Gender: 'Wanita',
    Usia: '35',
    Pendapatan_Tahunan_Ribuan_USD: '21',
    Pengeluaran_USD: '35',
  },
  {
    ID_Pelanggan: '18',
    Gender: 'Pria',
    Usia: '20',
    Pendapatan_Tahunan_Ribuan_USD: '21',
    Pengeluaran_USD: '66',
  },
  {
    ID_Pelanggan: '19',
    Gender: 'Pria',
    Usia: '52',
    Pendapatan_Tahunan_Ribuan_USD: '23',
    Pengeluaran_USD: '29',
  },
  {
    ID_Pelanggan: '20',
    Gender: 'Wanita',
    Usia: '35',
    Pendapatan_Tahunan_Ribuan_USD: '23',
    Pengeluaran_USD: '98',
  },
  {
    ID_Pelanggan: '21',
    Gender: 'Pria',
    Usia: '35',
    Pendapatan_Tahunan_Ribuan_USD: '24',
    Pengeluaran_USD: '35',
  },
  {
    ID_Pelanggan: '22',
    Gender: 'Pria',
    Usia: '25',
    Pendapatan_Tahunan_Ribuan_USD: '24',
    Pengeluaran_USD: '73',
  },
  {
    ID_Pelanggan: '23',
    Gender: 'Wanita',
    Usia: '46',
    Pendapatan_Tahunan_Ribuan_USD: '25',
    Pengeluaran_USD: '5',
  },
  {
    ID_Pelanggan: '24',
    Gender: 'Pria',
    Usia: '31',
    Pendapatan_Tahunan_Ribuan_USD: '25',
    Pengeluaran_USD: '73',
  },
  {
    ID_Pelanggan: '25',
    Gender: 'Wanita',
    Usia: '54',
    Pendapatan_Tahunan_Ribuan_USD: '28',
    Pengeluaran_USD: '14',
  },
  {
    ID_Pelanggan: '26',
    Gender: 'Pria',
    Usia: '29',
    Pendapatan_Tahunan_Ribuan_USD: '28',
    Pengeluaran_USD: '82',
  },
  {
    ID_Pelanggan: '27',
    Gender: 'Wanita',
    Usia: '45',
    Pendapatan_Tahunan_Ribuan_USD: '28',
    Pengeluaran_USD: '32',
  },
  {
    ID_Pelanggan: '28',
    Gender: 'Pria',
    Usia: '35',
    Pendapatan_Tahunan_Ribuan_USD: '28',
    Pengeluaran_USD: '61',
  },
  {
    ID_Pelanggan: '29',
    Gender: 'Wanita',
    Usia: '40',
    Pendapatan_Tahunan_Ribuan_USD: '29',
    Pengeluaran_USD: '31',
  },
  {
    ID_Pelanggan: '30',
    Gender: 'Wanita',
    Usia: '23',
    Pendapatan_Tahunan_Ribuan_USD: '29',
    Pengeluaran_USD: '87',
  },
  {
    ID_Pelanggan: '31',
    Gender: 'Pria',
    Usia: '60',
    Pendapatan_Tahunan_Ribuan_USD: '30',
    Pengeluaran_USD: '4',
  },
  {
    ID_Pelanggan: '32',
    Gender: 'Wanita',
    Usia: '21',
    Pendapatan_Tahunan_Ribuan_USD: '30',
    Pengeluaran_USD: '73',
  },
  {
    ID_Pelanggan: '33',
    Gender: 'Pria',
    Usia: '53',
    Pendapatan_Tahunan_Ribuan_USD: '33',
    Pengeluaran_USD: '4',
  },
  {
    ID_Pelanggan: '34',
    Gender: 'Pria',
    Usia: '18',
    Pendapatan_Tahunan_Ribuan_USD: '33',
    Pengeluaran_USD: '92',
  },
  {
    ID_Pelanggan: '35',
    Gender: 'Wanita',
    Usia: '49',
    Pendapatan_Tahunan_Ribuan_USD: '33',
    Pengeluaran_USD: '14',
  },
  {
    ID_Pelanggan: '36',
    Gender: 'Wanita',
    Usia: '21',
    Pendapatan_Tahunan_Ribuan_USD: '33',
    Pengeluaran_USD: '81',
  },
  {
    ID_Pelanggan: '37',
    Gender: 'Wanita',
    Usia: '42',
    Pendapatan_Tahunan_Ribuan_USD: '34',
    Pengeluaran_USD: '17',
  },
  {
    ID_Pelanggan: '38',
    Gender: 'Wanita',
    Usia: '30',
    Pendapatan_Tahunan_Ribuan_USD: '34',
    Pengeluaran_USD: '73',
  },
  {
    ID_Pelanggan: '39',
    Gender: 'Wanita',
    Usia: '36',
    Pendapatan_Tahunan_Ribuan_USD: '37',
    Pengeluaran_USD: '26',
  },
  {
    ID_Pelanggan: '40',
    Gender: 'Wanita',
    Usia: '20',
    Pendapatan_Tahunan_Ribuan_USD: '37',
    Pengeluaran_USD: '75',
  },
  {
    ID_Pelanggan: '41',
    Gender: 'Wanita',
    Usia: '65',
    Pendapatan_Tahunan_Ribuan_USD: '38',
    Pengeluaran_USD: '35',
  },
  {
    ID_Pelanggan: '42',
    Gender: 'Pria',
    Usia: '24',
    Pendapatan_Tahunan_Ribuan_USD: '38',
    Pengeluaran_USD: '92',
  },
  {
    ID_Pelanggan: '43',
    Gender: 'Pria',
    Usia: '48',
    Pendapatan_Tahunan_Ribuan_USD: '39',
    Pengeluaran_USD: '36',
  },
  {
    ID_Pelanggan: '44',
    Gender: 'Wanita',
    Usia: '31',
    Pendapatan_Tahunan_Ribuan_USD: '39',
    Pengeluaran_USD: '61',
  },
  {
    ID_Pelanggan: '45',
    Gender: 'Wanita',
    Usia: '49',
    Pendapatan_Tahunan_Ribuan_USD: '39',
    Pengeluaran_USD: '28',
  },
  {
    ID_Pelanggan: '46',
    Gender: 'Wanita',
    Usia: '24',
    Pendapatan_Tahunan_Ribuan_USD: '39',
    Pengeluaran_USD: '65',
  },
  {
    ID_Pelanggan: '47',
    Gender: 'Wanita',
    Usia: '50',
    Pendapatan_Tahunan_Ribuan_USD: '40',
    Pengeluaran_USD: '55',
  },
  {
    ID_Pelanggan: '48',
    Gender: 'Wanita',
    Usia: '27',
    Pendapatan_Tahunan_Ribuan_USD: '40',
    Pengeluaran_USD: '47',
  },
  {
    ID_Pelanggan: '49',
    Gender: 'Wanita',
    Usia: '29',
    Pendapatan_Tahunan_Ribuan_USD: '40',
    Pengeluaran_USD: '42',
  },
  {
    ID_Pelanggan: '50',
    Gender: 'Wanita',
    Usia: '31',
    Pendapatan_Tahunan_Ribuan_USD: '40',
    Pengeluaran_USD: '42',
  },
  {
    ID_Pelanggan: '51',
    Gender: 'Wanita',
    Usia: '49',
    Pendapatan_Tahunan_Ribuan_USD: '42',
    Pengeluaran_USD: '52',
  },
  {
    ID_Pelanggan: '52',
    Gender: 'Pria',
    Usia: '33',
    Pendapatan_Tahunan_Ribuan_USD: '42',
    Pengeluaran_USD: '60',
  },
  {
    ID_Pelanggan: '53',
    Gender: 'Wanita',
    Usia: '31',
    Pendapatan_Tahunan_Ribuan_USD: '43',
    Pengeluaran_USD: '54',
  },
  {
    ID_Pelanggan: '54',
    Gender: 'Pria',
    Usia: '59',
    Pendapatan_Tahunan_Ribuan_USD: '43',
    Pengeluaran_USD: '60',
  },
  {
    ID_Pelanggan: '55',
    Gender: 'Wanita',
    Usia: '50',
    Pendapatan_Tahunan_Ribuan_USD: '43',
    Pengeluaran_USD: '45',
  },
  {
    ID_Pelanggan: '56',
    Gender: 'Pria',
    Usia: '47',
    Pendapatan_Tahunan_Ribuan_USD: '43',
    Pengeluaran_USD: '41',
  },
  {
    ID_Pelanggan: '57',
    Gender: 'Wanita',
    Usia: '51',
    Pendapatan_Tahunan_Ribuan_USD: '44',
    Pengeluaran_USD: '50',
  },
  {
    ID_Pelanggan: '58',
    Gender: 'Pria',
    Usia: '69',
    Pendapatan_Tahunan_Ribuan_USD: '44',
    Pengeluaran_USD: '46',
  },
  {
    ID_Pelanggan: '59',
    Gender: 'Wanita',
    Usia: '27',
    Pendapatan_Tahunan_Ribuan_USD: '46',
    Pengeluaran_USD: '51',
  },
  {
    ID_Pelanggan: '60',
    Gender: 'Pria',
    Usia: '53',
    Pendapatan_Tahunan_Ribuan_USD: '46',
    Pengeluaran_USD: '46',
  },
  {
    ID_Pelanggan: '61',
    Gender: 'Pria',
    Usia: '70',
    Pendapatan_Tahunan_Ribuan_USD: '46',
    Pengeluaran_USD: '56',
  },
  {
    ID_Pelanggan: '62',
    Gender: 'Pria',
    Usia: '19',
    Pendapatan_Tahunan_Ribuan_USD: '46',
    Pengeluaran_USD: '55',
  },
  {
    ID_Pelanggan: '63',
    Gender: 'Wanita',
    Usia: '67',
    Pendapatan_Tahunan_Ribuan_USD: '47',
    Pengeluaran_USD: '52',
  },
  {
    ID_Pelanggan: '64',
    Gender: 'Wanita',
    Usia: '54',
    Pendapatan_Tahunan_Ribuan_USD: '47',
    Pengeluaran_USD: '59',
  },
  {
    ID_Pelanggan: '65',
    Gender: 'Pria',
    Usia: '63',
    Pendapatan_Tahunan_Ribuan_USD: '48',
    Pengeluaran_USD: '51',
  },
  {
    ID_Pelanggan: '66',
    Gender: 'Pria',
    Usia: '18',
    Pendapatan_Tahunan_Ribuan_USD: '48',
    Pengeluaran_USD: '59',
  },
  {
    ID_Pelanggan: '67',
    Gender: 'Wanita',
    Usia: '43',
    Pendapatan_Tahunan_Ribuan_USD: '48',
    Pengeluaran_USD: '50',
  },
  {
    ID_Pelanggan: '68',
    Gender: 'Wanita',
    Usia: '68',
    Pendapatan_Tahunan_Ribuan_USD: '48',
    Pengeluaran_USD: '48',
  },
  {
    ID_Pelanggan: '69',
    Gender: 'Pria',
    Usia: '19',
    Pendapatan_Tahunan_Ribuan_USD: '48',
    Pengeluaran_USD: '59',
  },
  {
    ID_Pelanggan: '70',
    Gender: 'Wanita',
    Usia: '32',
    Pendapatan_Tahunan_Ribuan_USD: '48',
    Pengeluaran_USD: '47',
  },
  {
    ID_Pelanggan: '71',
    Gender: 'Pria',
    Usia: '70',
    Pendapatan_Tahunan_Ribuan_USD: '49',
    Pengeluaran_USD: '55',
  },
  {
    ID_Pelanggan: '72',
    Gender: 'Wanita',
    Usia: '47',
    Pendapatan_Tahunan_Ribuan_USD: '49',
    Pengeluaran_USD: '42',
  },
  {
    ID_Pelanggan: '73',
    Gender: 'Wanita',
    Usia: '60',
    Pendapatan_Tahunan_Ribuan_USD: '50',
    Pengeluaran_USD: '49',
  },
  {
    ID_Pelanggan: '74',
    Gender: 'Wanita',
    Usia: '60',
    Pendapatan_Tahunan_Ribuan_USD: '50',
    Pengeluaran_USD: '56',
  },
  {
    ID_Pelanggan: '75',
    Gender: 'Pria',
    Usia: '59',
    Pendapatan_Tahunan_Ribuan_USD: '54',
    Pengeluaran_USD: '47',
  },
  {
    ID_Pelanggan: '76',
    Gender: 'Pria',
    Usia: '26',
    Pendapatan_Tahunan_Ribuan_USD: '54',
    Pengeluaran_USD: '54',
  },
  {
    ID_Pelanggan: '77',
    Gender: 'Wanita',
    Usia: '45',
    Pendapatan_Tahunan_Ribuan_USD: '54',
    Pengeluaran_USD: '53',
  },
  {
    ID_Pelanggan: '78',
    Gender: 'Pria',
    Usia: '40',
    Pendapatan_Tahunan_Ribuan_USD: '54',
    Pengeluaran_USD: '48',
  },
  {
    ID_Pelanggan: '79',
    Gender: 'Wanita',
    Usia: '23',
    Pendapatan_Tahunan_Ribuan_USD: '54',
    Pengeluaran_USD: '52',
  },
  {
    ID_Pelanggan: '80',
    Gender: 'Wanita',
    Usia: '49',
    Pendapatan_Tahunan_Ribuan_USD: '54',
    Pengeluaran_USD: '42',
  },
  {
    ID_Pelanggan: '81',
    Gender: 'Pria',
    Usia: '57',
    Pendapatan_Tahunan_Ribuan_USD: '54',
    Pengeluaran_USD: '51',
  },
  {
    ID_Pelanggan: '82',
    Gender: 'Pria',
    Usia: '38',
    Pendapatan_Tahunan_Ribuan_USD: '54',
    Pengeluaran_USD: '55',
  },
  {
    ID_Pelanggan: '83',
    Gender: 'Pria',
    Usia: '67',
    Pendapatan_Tahunan_Ribuan_USD: '54',
    Pengeluaran_USD: '41',
  },
  {
    ID_Pelanggan: '84',
    Gender: 'Wanita',
    Usia: '46',
    Pendapatan_Tahunan_Ribuan_USD: '54',
    Pengeluaran_USD: '44',
  },
  {
    ID_Pelanggan: '85',
    Gender: 'Wanita',
    Usia: '21',
    Pendapatan_Tahunan_Ribuan_USD: '54',
    Pengeluaran_USD: '57',
  },
  {
    ID_Pelanggan: '86',
    Gender: 'Pria',
    Usia: '48',
    Pendapatan_Tahunan_Ribuan_USD: '54',
    Pengeluaran_USD: '46',
  },
  {
    ID_Pelanggan: '87',
    Gender: 'Wanita',
    Usia: '55',
    Pendapatan_Tahunan_Ribuan_USD: '57',
    Pengeluaran_USD: '58',
  },
  {
    ID_Pelanggan: '88',
    Gender: 'Wanita',
    Usia: '22',
    Pendapatan_Tahunan_Ribuan_USD: '57',
    Pengeluaran_USD: '55',
  },
  {
    ID_Pelanggan: '89',
    Gender: 'Wanita',
    Usia: '34',
    Pendapatan_Tahunan_Ribuan_USD: '58',
    Pengeluaran_USD: '60',
  },
  {
    ID_Pelanggan: '90',
    Gender: 'Wanita',
    Usia: '50',
    Pendapatan_Tahunan_Ribuan_USD: '58',
    Pengeluaran_USD: '46',
  },
  {
    ID_Pelanggan: '91',
    Gender: 'Wanita',
    Usia: '68',
    Pendapatan_Tahunan_Ribuan_USD: '59',
    Pengeluaran_USD: '55',
  },
  {
    ID_Pelanggan: '92',
    Gender: 'Pria',
    Usia: '18',
    Pendapatan_Tahunan_Ribuan_USD: '59',
    Pengeluaran_USD: '41',
  },
  {
    ID_Pelanggan: '93',
    Gender: 'Pria',
    Usia: '48',
    Pendapatan_Tahunan_Ribuan_USD: '60',
    Pengeluaran_USD: '49',
  },
  {
    ID_Pelanggan: '94',
    Gender: 'Wanita',
    Usia: '40',
    Pendapatan_Tahunan_Ribuan_USD: '60',
    Pengeluaran_USD: '40',
  },
  {
    ID_Pelanggan: '95',
    Gender: 'Wanita',
    Usia: '32',
    Pendapatan_Tahunan_Ribuan_USD: '60',
    Pengeluaran_USD: '42',
  },
  {
    ID_Pelanggan: '96',
    Gender: 'Pria',
    Usia: '24',
    Pendapatan_Tahunan_Ribuan_USD: '60',
    Pengeluaran_USD: '52',
  },
  {
    ID_Pelanggan: '97',
    Gender: 'Wanita',
    Usia: '47',
    Pendapatan_Tahunan_Ribuan_USD: '60',
    Pengeluaran_USD: '47',
  },
  {
    ID_Pelanggan: '98',
    Gender: 'Wanita',
    Usia: '27',
    Pendapatan_Tahunan_Ribuan_USD: '60',
    Pengeluaran_USD: '50',
  },
  {
    ID_Pelanggan: '99',
    Gender: 'Pria',
    Usia: '48',
    Pendapatan_Tahunan_Ribuan_USD: '61',
    Pengeluaran_USD: '42',
  },
  {
    ID_Pelanggan: '100',
    Gender: 'Pria',
    Usia: '20',
    Pendapatan_Tahunan_Ribuan_USD: '61',
    Pengeluaran_USD: '49',
  },

  {
    ID_Pelanggan: '101',
    Gender: 'Wanita',
    Usia: '23',
    Pendapatan_Tahunan_Ribuan_USD: '62',
    Pengeluaran_USD: '41',
  },
  {
    ID_Pelanggan: '102',
    Gender: 'Wanita',
    Usia: '49',
    Pendapatan_Tahunan_Ribuan_USD: '62',
    Pengeluaran_USD: '48',
  },
  {
    ID_Pelanggan: '103',
    Gender: 'Pria',
    Usia: '67',
    Pendapatan_Tahunan_Ribuan_USD: '62',
    Pengeluaran_USD: '59',
  },
  {
    ID_Pelanggan: '104',
    Gender: 'Pria',
    Usia: '26',
    Pendapatan_Tahunan_Ribuan_USD: '62',
    Pengeluaran_USD: '55',
  },
  {
    ID_Pelanggan: '105',
    Gender: 'Pria',
    Usia: '49',
    Pendapatan_Tahunan_Ribuan_USD: '62',
    Pengeluaran_USD: '56',
  },
  {
    ID_Pelanggan: '106',
    Gender: 'Wanita',
    Usia: '21',
    Pendapatan_Tahunan_Ribuan_USD: '62',
    Pengeluaran_USD: '42',
  },
  {
    ID_Pelanggan: '107',
    Gender: 'Wanita',
    Usia: '66',
    Pendapatan_Tahunan_Ribuan_USD: '63',
    Pengeluaran_USD: '50',
  },
  {
    ID_Pelanggan: '108',
    Gender: 'Pria',
    Usia: '54',
    Pendapatan_Tahunan_Ribuan_USD: '63',
    Pengeluaran_USD: '46',
  },
  {
    ID_Pelanggan: '109',
    Gender: 'Pria',
    Usia: '68',
    Pendapatan_Tahunan_Ribuan_USD: '63',
    Pengeluaran_USD: '43',
  },
  {
    ID_Pelanggan: '110',
    Gender: 'Pria',
    Usia: '66',
    Pendapatan_Tahunan_Ribuan_USD: '63',
    Pengeluaran_USD: '48',
  },
  {
    ID_Pelanggan: '111',
    Gender: 'Pria',
    Usia: '65',
    Pendapatan_Tahunan_Ribuan_USD: '63',
    Pengeluaran_USD: '52',
  },
  {
    ID_Pelanggan: '112',
    Gender: 'Wanita',
    Usia: '19',
    Pendapatan_Tahunan_Ribuan_USD: '63',
    Pengeluaran_USD: '54',
  },
  {
    ID_Pelanggan: '113',
    Gender: 'Wanita',
    Usia: '38',
    Pendapatan_Tahunan_Ribuan_USD: '64',
    Pengeluaran_USD: '42',
  },
  {
    ID_Pelanggan: '114',
    Gender: 'Pria',
    Usia: '19',
    Pendapatan_Tahunan_Ribuan_USD: '64',
    Pengeluaran_USD: '46',
  },
  {
    ID_Pelanggan: '115',
    Gender: 'Wanita',
    Usia: '18',
    Pendapatan_Tahunan_Ribuan_USD: '65',
    Pengeluaran_USD: '48',
  },
  {
    ID_Pelanggan: '116',
    Gender: 'Wanita',
    Usia: '19',
    Pendapatan_Tahunan_Ribuan_USD: '65',
    Pengeluaran_USD: '50',
  },
  {
    ID_Pelanggan: '117',
    Gender: 'Wanita',
    Usia: '63',
    Pendapatan_Tahunan_Ribuan_USD: '65',
    Pengeluaran_USD: '43',
  },
  {
    ID_Pelanggan: '118',
    Gender: 'Wanita',
    Usia: '49',
    Pendapatan_Tahunan_Ribuan_USD: '65',
    Pengeluaran_USD: '59',
  },
  {
    ID_Pelanggan: '119',
    Gender: 'Wanita',
    Usia: '51',
    Pendapatan_Tahunan_Ribuan_USD: '67',
    Pengeluaran_USD: '43',
  },
  {
    ID_Pelanggan: '120',
    Gender: 'Wanita',
    Usia: '50',
    Pendapatan_Tahunan_Ribuan_USD: '67',
    Pengeluaran_USD: '57',
  },
  {
    ID_Pelanggan: '121',
    Gender: 'Pria',
    Usia: '27',
    Pendapatan_Tahunan_Ribuan_USD: '67',
    Pengeluaran_USD: '56',
  },
  {
    ID_Pelanggan: '122',
    Gender: 'Wanita',
    Usia: '38',
    Pendapatan_Tahunan_Ribuan_USD: '67',
    Pengeluaran_USD: '40',
  },
  {
    ID_Pelanggan: '123',
    Gender: 'Wanita',
    Usia: '40',
    Pendapatan_Tahunan_Ribuan_USD: '69',
    Pengeluaran_USD: '58',
  },
  {
    ID_Pelanggan: '124',
    Gender: 'Pria',
    Usia: '39',
    Pendapatan_Tahunan_Ribuan_USD: '69',
    Pengeluaran_USD: '91',
  },
  {
    ID_Pelanggan: '125',
    Gender: 'Wanita',
    Usia: '23',
    Pendapatan_Tahunan_Ribuan_USD: '70',
    Pengeluaran_USD: '29',
  },
  {
    ID_Pelanggan: '126',
    Gender: 'Wanita',
    Usia: '31',
    Pendapatan_Tahunan_Ribuan_USD: '70',
    Pengeluaran_USD: '77',
  },
  {
    ID_Pelanggan: '127',
    Gender: 'Pria',
    Usia: '43',
    Pendapatan_Tahunan_Ribuan_USD: '71',
    Pengeluaran_USD: '35',
  },
  {
    ID_Pelanggan: '128',
    Gender: 'Pria',
    Usia: '40',
    Pendapatan_Tahunan_Ribuan_USD: '71',
    Pengeluaran_USD: '95',
  },
  {
    ID_Pelanggan: '129',
    Gender: 'Pria',
    Usia: '59',
    Pendapatan_Tahunan_Ribuan_USD: '71',
    Pengeluaran_USD: '11',
  },
  {
    ID_Pelanggan: '130',
    Gender: 'Pria',
    Usia: '38',
    Pendapatan_Tahunan_Ribuan_USD: '71',
    Pengeluaran_USD: '75',
  },
  {
    ID_Pelanggan: '131',
    Gender: 'Pria',
    Usia: '47',
    Pendapatan_Tahunan_Ribuan_USD: '71',
    Pengeluaran_USD: '9',
  },
  {
    ID_Pelanggan: '132',
    Gender: 'Pria',
    Usia: '39',
    Pendapatan_Tahunan_Ribuan_USD: '71',
    Pengeluaran_USD: '75',
  },
  {
    ID_Pelanggan: '133',
    Gender: 'Wanita',
    Usia: '25',
    Pendapatan_Tahunan_Ribuan_USD: '72',
    Pengeluaran_USD: '34',
  },
  {
    ID_Pelanggan: '134',
    Gender: 'Wanita',
    Usia: '31',
    Pendapatan_Tahunan_Ribuan_USD: '72',
    Pengeluaran_USD: '71',
  },
  {
    ID_Pelanggan: '135',
    Gender: 'Pria',
    Usia: '20',
    Pendapatan_Tahunan_Ribuan_USD: '73',
    Pengeluaran_USD: '5',
  },
  {
    ID_Pelanggan: '136',
    Gender: 'Wanita',
    Usia: '29',
    Pendapatan_Tahunan_Ribuan_USD: '73',
    Pengeluaran_USD: '88',
  },
  {
    ID_Pelanggan: '137',
    Gender: 'Wanita',
    Usia: '44',
    Pendapatan_Tahunan_Ribuan_USD: '73',
    Pengeluaran_USD: '7',
  },
  {
    ID_Pelanggan: '138',
    Gender: 'Pria',
    Usia: '32',
    Pendapatan_Tahunan_Ribuan_USD: '73',
    Pengeluaran_USD: '73',
  },
  {
    ID_Pelanggan: '139',
    Gender: 'Pria',
    Usia: '19',
    Pendapatan_Tahunan_Ribuan_USD: '74',
    Pengeluaran_USD: '10',
  },
  {
    ID_Pelanggan: '140',
    Gender: 'Wanita',
    Usia: '35',
    Pendapatan_Tahunan_Ribuan_USD: '74',
    Pengeluaran_USD: '72',
  },
  {
    ID_Pelanggan: '141',
    Gender: 'Wanita',
    Usia: '57',
    Pendapatan_Tahunan_Ribuan_USD: '75',
    Pengeluaran_USD: '5',
  },
  {
    ID_Pelanggan: '142',
    Gender: 'Pria',
    Usia: '32',
    Pendapatan_Tahunan_Ribuan_USD: '75',
    Pengeluaran_USD: '93',
  },
  {
    ID_Pelanggan: '143',
    Gender: 'Wanita',
    Usia: '28',
    Pendapatan_Tahunan_Ribuan_USD: '76',
    Pengeluaran_USD: '40',
  },
  {
    ID_Pelanggan: '144',
    Gender: 'Wanita',
    Usia: '32',
    Pendapatan_Tahunan_Ribuan_USD: '76',
    Pengeluaran_USD: '87',
  },
  {
    ID_Pelanggan: '145',
    Gender: 'Pria',
    Usia: '25',
    Pendapatan_Tahunan_Ribuan_USD: '77',
    Pengeluaran_USD: '12',
  },
  {
    ID_Pelanggan: '146',
    Gender: 'Pria',
    Usia: '28',
    Pendapatan_Tahunan_Ribuan_USD: '77',
    Pengeluaran_USD: '97',
  },
  {
    ID_Pelanggan: '147',
    Gender: 'Pria',
    Usia: '48',
    Pendapatan_Tahunan_Ribuan_USD: '77',
    Pengeluaran_USD: '36',
  },
  {
    ID_Pelanggan: '148',
    Gender: 'Wanita',
    Usia: '32',
    Pendapatan_Tahunan_Ribuan_USD: '77',
    Pengeluaran_USD: '74',
  },
  {
    ID_Pelanggan: '149',
    Gender: 'Wanita',
    Usia: '34',
    Pendapatan_Tahunan_Ribuan_USD: '78',
    Pengeluaran_USD: '22',
  },
  {
    ID_Pelanggan: '150',
    Gender: 'Pria',
    Usia: '34',
    Pendapatan_Tahunan_Ribuan_USD: '78',
    Pengeluaran_USD: '90',
  },
  {
    ID_Pelanggan: '151',
    Gender: 'Pria',
    Usia: '43',
    Pendapatan_Tahunan_Ribuan_USD: '78',
    Pengeluaran_USD: '17',
  },
  {
    ID_Pelanggan: '152',
    Gender: 'Pria',
    Usia: '39',
    Pendapatan_Tahunan_Ribuan_USD: '78',
    Pengeluaran_USD: '88',
  },
  {
    ID_Pelanggan: '153',
    Gender: 'Wanita',
    Usia: '44',
    Pendapatan_Tahunan_Ribuan_USD: '78',
    Pengeluaran_USD: '20',
  },
  {
    ID_Pelanggan: '154',
    Gender: 'Wanita',
    Usia: '38',
    Pendapatan_Tahunan_Ribuan_USD: '78',
    Pengeluaran_USD: '76',
  },
  {
    ID_Pelanggan: '155',
    Gender: 'Wanita',
    Usia: '47',
    Pendapatan_Tahunan_Ribuan_USD: '78',
    Pengeluaran_USD: '16',
  },
  {
    ID_Pelanggan: '156',
    Gender: 'Wanita',
    Usia: '27',
    Pendapatan_Tahunan_Ribuan_USD: '78',
    Pengeluaran_USD: '89',
  },
  {
    ID_Pelanggan: '157',
    Gender: 'Pria',
    Usia: '37',
    Pendapatan_Tahunan_Ribuan_USD: '78',
    Pengeluaran_USD: '1',
  },
  {
    ID_Pelanggan: '158',
    Gender: 'Wanita',
    Usia: '30',
    Pendapatan_Tahunan_Ribuan_USD: '78',
    Pengeluaran_USD: '78',
  },
  {
    ID_Pelanggan: '159',
    Gender: 'Pria',
    Usia: '34',
    Pendapatan_Tahunan_Ribuan_USD: '78',
    Pengeluaran_USD: '1',
  },
  {
    ID_Pelanggan: '160',
    Gender: 'Wanita',
    Usia: '30',
    Pendapatan_Tahunan_Ribuan_USD: '78',
    Pengeluaran_USD: '73',
  },
  {
    ID_Pelanggan: '161',
    Gender: 'Wanita',
    Usia: '56',
    Pendapatan_Tahunan_Ribuan_USD: '79',
    Pengeluaran_USD: '35',
  },
  {
    ID_Pelanggan: '162',
    Gender: 'Wanita',
    Usia: '29',
    Pendapatan_Tahunan_Ribuan_USD: '79',
    Pengeluaran_USD: '83',
  },
  {
    ID_Pelanggan: '163',
    Gender: 'Pria',
    Usia: '19',
    Pendapatan_Tahunan_Ribuan_USD: '81',
    Pengeluaran_USD: '5',
  },
  {
    ID_Pelanggan: '164',
    Gender: 'Wanita',
    Usia: '31',
    Pendapatan_Tahunan_Ribuan_USD: '81',
    Pengeluaran_USD: '93',
  },
  {
    ID_Pelanggan: '165',
    Gender: 'Pria',
    Usia: '50',
    Pendapatan_Tahunan_Ribuan_USD: '85',
    Pengeluaran_USD: '26',
  },
  {
    ID_Pelanggan: '166',
    Gender: 'Wanita',
    Usia: '36',
    Pendapatan_Tahunan_Ribuan_USD: '85',
    Pengeluaran_USD: '75',
  },
  {
    ID_Pelanggan: '167',
    Gender: 'Pria',
    Usia: '42',
    Pendapatan_Tahunan_Ribuan_USD: '86',
    Pengeluaran_USD: '20',
  },
  {
    ID_Pelanggan: '168',
    Gender: 'Wanita',
    Usia: '33',
    Pendapatan_Tahunan_Ribuan_USD: '86',
    Pengeluaran_USD: '95',
  },
  {
    ID_Pelanggan: '169',
    Gender: 'Wanita',
    Usia: '36',
    Pendapatan_Tahunan_Ribuan_USD: '87',
    Pengeluaran_USD: '27',
  },
  {
    ID_Pelanggan: '170',
    Gender: 'Pria',
    Usia: '32',
    Pendapatan_Tahunan_Ribuan_USD: '87',
    Pengeluaran_USD: '63',
  },
  {
    ID_Pelanggan: '171',
    Gender: 'Pria',
    Usia: '40',
    Pendapatan_Tahunan_Ribuan_USD: '87',
    Pengeluaran_USD: '13',
  },
  {
    ID_Pelanggan: '172',
    Gender: 'Pria',
    Usia: '28',
    Pendapatan_Tahunan_Ribuan_USD: '87',
    Pengeluaran_USD: '75',
  },
  {
    ID_Pelanggan: '173',
    Gender: 'Pria',
    Usia: '36',
    Pendapatan_Tahunan_Ribuan_USD: '87',
    Pengeluaran_USD: '10',
  },
  {
    ID_Pelanggan: '174',
    Gender: 'Pria',
    Usia: '36',
    Pendapatan_Tahunan_Ribuan_USD: '87',
    Pengeluaran_USD: '92',
  },
  {
    ID_Pelanggan: '175',
    Gender: 'Wanita',
    Usia: '52',
    Pendapatan_Tahunan_Ribuan_USD: '88',
    Pengeluaran_USD: '13',
  },
  {
    ID_Pelanggan: '176',
    Gender: 'Wanita',
    Usia: '30',
    Pendapatan_Tahunan_Ribuan_USD: '88',
    Pengeluaran_USD: '86',
  },
  {
    ID_Pelanggan: '177',
    Gender: 'Pria',
    Usia: '58',
    Pendapatan_Tahunan_Ribuan_USD: '88',
    Pengeluaran_USD: '15',
  },
  {
    ID_Pelanggan: '178',
    Gender: 'Pria',
    Usia: '27',
    Pendapatan_Tahunan_Ribuan_USD: '88',
    Pengeluaran_USD: '69',
  },
  {
    ID_Pelanggan: '179',
    Gender: 'Pria',
    Usia: '59',
    Pendapatan_Tahunan_Ribuan_USD: '93',
    Pengeluaran_USD: '14',
  },
  {
    ID_Pelanggan: '180',
    Gender: 'Pria',
    Usia: '35',
    Pendapatan_Tahunan_Ribuan_USD: '93',
    Pengeluaran_USD: '90',
  },
  {
    ID_Pelanggan: '181',
    Gender: 'Wanita',
    Usia: '37',
    Pendapatan_Tahunan_Ribuan_USD: '97',
    Pengeluaran_USD: '32',
  },
  {
    ID_Pelanggan: '182',
    Gender: 'Wanita',
    Usia: '32',
    Pendapatan_Tahunan_Ribuan_USD: '97',
    Pengeluaran_USD: '86',
  },
  {
    ID_Pelanggan: '183',
    Gender: 'Pria',
    Usia: '46',
    Pendapatan_Tahunan_Ribuan_USD: '98',
    Pengeluaran_USD: '15',
  },
  {
    ID_Pelanggan: '184',
    Gender: 'Wanita',
    Usia: '29',
    Pendapatan_Tahunan_Ribuan_USD: '98',
    Pengeluaran_USD: '88',
  },
  {
    ID_Pelanggan: '185',
    Gender: 'Wanita',
    Usia: '41',
    Pendapatan_Tahunan_Ribuan_USD: '99',
    Pengeluaran_USD: '39',
  },
  {
    ID_Pelanggan: '186',
    Gender: 'Pria',
    Usia: '30',
    Pendapatan_Tahunan_Ribuan_USD: '99',
    Pengeluaran_USD: '97',
  },
  {
    ID_Pelanggan: '187',
    Gender: 'Wanita',
    Usia: '54',
    Pendapatan_Tahunan_Ribuan_USD: '101',
    Pengeluaran_USD: '24',
  },
  {
    ID_Pelanggan: '188',
    Gender: 'Pria',
    Usia: '28',
    Pendapatan_Tahunan_Ribuan_USD: '101',
    Pengeluaran_USD: '68',
  },
  {
    ID_Pelanggan: '189',
    Gender: 'Wanita',
    Usia: '41',
    Pendapatan_Tahunan_Ribuan_USD: '103',
    Pengeluaran_USD: '17',
  },
  {
    ID_Pelanggan: '190',
    Gender: 'Wanita',
    Usia: '36',
    Pendapatan_Tahunan_Ribuan_USD: '103',
    Pengeluaran_USD: '85',
  },
  {
    ID_Pelanggan: '191',
    Gender: 'Wanita',
    Usia: '34',
    Pendapatan_Tahunan_Ribuan_USD: '103',
    Pengeluaran_USD: '23',
  },
  {
    ID_Pelanggan: '192',
    Gender: 'Wanita',
    Usia: '32',
    Pendapatan_Tahunan_Ribuan_USD: '103',
    Pengeluaran_USD: '69',
  },
  {
    ID_Pelanggan: '193',
    Gender: 'Pria',
    Usia: '33',
    Pendapatan_Tahunan_Ribuan_USD: '113',
    Pengeluaran_USD: '8',
  },
  {
    ID_Pelanggan: '194',
    Gender: 'Wanita',
    Usia: '38',
    Pendapatan_Tahunan_Ribuan_USD: '113',
    Pengeluaran_USD: '91',
  },
  {
    ID_Pelanggan: '195',
    Gender: 'Wanita',
    Usia: '47',
    Pendapatan_Tahunan_Ribuan_USD: '120',
    Pengeluaran_USD: '16',
  },
  {
    ID_Pelanggan: '196',
    Gender: 'Wanita',
    Usia: '35',
    Pendapatan_Tahunan_Ribuan_USD: '120',
    Pengeluaran_USD: '79',
  },
  {
    ID_Pelanggan: '197',
    Gender: 'Wanita',
    Usia: '45',
    Pendapatan_Tahunan_Ribuan_USD: '126',
    Pengeluaran_USD: '28',
  },
  {
    ID_Pelanggan: '198',
    Gender: 'Pria',
    Usia: '32',
    Pendapatan_Tahunan_Ribuan_USD: '126',
    Pengeluaran_USD: '74',
  },
  {
    ID_Pelanggan: '199',
    Gender: 'Pria',
    Usia: '32',
    Pendapatan_Tahunan_Ribuan_USD: '137',
    Pengeluaran_USD: '18',
  },
  {
    ID_Pelanggan: '200',
    Gender: 'Pria',
    Usia: '30',
    Pendapatan_Tahunan_Ribuan_USD: '137',
    Pengeluaran_USD: '83',
  },
];

export { PengunjungMall };
